[build]
builder = "DOCKERFILE"
dockerfilePath = "src/Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/applications"
healthcheckTimeout = 100
